service:
  name: agromasc-serverless

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local
  #- serverless-offline-sqs

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true
  #serverless-offline-sqs:
   # autoCreate: true                 # create queue if not exists
    #apiVersion: '2012-11-05'
    #endpoint: http://0.0.0.0:9324
    #region: eu-west-1
    #accessKeyId: root
    #secretAccessKey: root
    #skipCacheInvalidation: false

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource: "*"
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
    - Effect: Allow
      Action:
        - sqs:*
      Resource: "*"

functions:
  healthCheck:
    handler: src/shared/functions/healthCheck.handler
    events:
      - http:
          path: /healthCheck
          method: GET
          cors: true
  createUser:
    handler: src/shared/functions/createUser.handler
    events:
      - http:
          path: /users
          method: POST
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:PutItem
        Resource: "arn:aws:dynamodb:${self.provider.region}:*:table/agromasc"
  getUser:
    handler: src/shared/functions/getUsers.handler
    events:
      - http:
          path: /users
          method: GET
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: "arn:aws:dynamodb:${self.provider.region}:*:table/agromasc"
  #logSqs:
    #handler: src/shared/functions/log.handler
   # events:
    #  sqs: arn:aws:sqs:region:us-east-1:MyFirstQueue

resources:
  Resources:
    dynamoDbAgroMasc:
      Type: AWS::DynamoDB::Table
      Properties:
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: agromasc
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: kind
            AttributeType: S
        KeySchema:
          - AttributeName: kind
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
          